# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en

timezone: Africa/Cairo
baseurl: ""

title: 0xW0W
tagline: Documenting my pentest journey
description: Android security, CTFs, and pentest writeups.

url: "https://wesam98.github.io"

github:
  username: wesam98

social:
  name: Wesam Abdelaziz
  email: wesamabdelaziz009@gmail.com
  links:
    - https://github.com/wesam98
    - https://www.linkedin.com/in/wesam-abd-el-aziz-224b3a245/

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode: dark

cdn:

avatar: assets/download (10).jpg

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    e
